### ISSUE TITLE
pip install windows-curses does not work in Windows 11

### ISSUE THREAD

**Issue by brentmparker** [zephyrproject-rtos/windows-curses#27] opened 2021-11-10 07:26 UTC
My student recently upgraded his OS from Win10 to WIn11. Before the upgrade, windows-curses installed without trouble. After the upgrade, it will not install. 

To verify this I tried it on another Win11 computer. Same problem. The error it reports is:

pip install windows-curses
ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)
ERROR: No matching distributions found for windows-curses

pip install windows-curses==2.2.0
ERROR: Could not find a version that satisfies the requirement windows-curses==2.2.0 (from versions: none)
ERROR: No matching distributions found for windows-curses

I even attempted to download the wheel file directly and install that. It reports

ERROR: windows_curses-2.2.0-cp39-win_amd64.whl is not a supported wheel on this platform

**Comment by MartyMacGyver** [comment] 2021-11-10 08:40
Interesting.... I just got that problem with trying to install `windows-curses` on Python 3.10 on Windows 10 for ESP32 work - long story short, `windows-curses` is not available for 3.10 yet. So I wonder if you are actually using Python 3.10: what's the output of `pip --version`?

**Comment by brentmparker** [comment] 2021-11-10 12:43
As they just upgraded earlier this week and installed the latest Python, I'm pretty sure they are running Python 3.10.  I'll have to double check tomorrow, but that is it.  Any clue when it might be available for 3.10?

Btw, Love the username and the avatar.

**Comment by MartyMacGyver** [comment] 2021-11-10 17:50
No idea - I came here myself to find out if a 3.10 version is in the works, but it doesn't seem like there's been any activity here for a while.

**Comment by yazid-kandi** [comment] 2021-11-13 19:08
experiencing the same issue on windows 10, python 3.10.0 
```ERROR: Could not find a version that satisfies the requirement windows-curses (from versions: none)```
```ERROR: No matching distribution found for windows-curses```

but it's seems like [latest updates](https://pypi.org/project/windows-curses/#files) has been a year ago, so i'm guessing we'll be sticking with py3.9 for some longer time.

**Comment by Rexcrispy** [comment] 2021-11-14 04:48
Having the same issue as well Windows 11 Python 3.10.0

**Comment by carlescufi** [comment] 2021-11-24 16:38
Duplicate of #26

**Closed by carlescufi** 2021-11-24 16:38 UTC
